# Generated by Django 5.1.5 on 2025-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ep_crm1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(),
        ),
    ]
